/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppTagsEditRouteImport } from './routes/app/tagsEdit'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppPostauthRouteImport } from './routes/app/postauth'
import { Route as AppInitiativesRouteImport } from './routes/app/initiatives'
import { Route as AppWorklistIndexRouteImport } from './routes/app/worklist/index'
import { Route as AppWorklistSubtasksWorkItemIdRouteImport } from './routes/app/worklist/subtasks/$workItemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTagsEditRoute = AppTagsEditRouteImport.update({
  id: '/app/tagsEdit',
  path: '/app/tagsEdit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostauthRoute = AppPostauthRouteImport.update({
  id: '/app/postauth',
  path: '/app/postauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInitiativesRoute = AppInitiativesRouteImport.update({
  id: '/app/initiatives',
  path: '/app/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorklistIndexRoute = AppWorklistIndexRouteImport.update({
  id: '/app/worklist/',
  path: '/app/worklist/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorklistSubtasksWorkItemIdRoute =
  AppWorklistSubtasksWorkItemIdRouteImport.update({
    id: '/app/worklist/subtasks/$workItemId',
    path: '/app/worklist/subtasks/$workItemId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/initiatives': typeof AppInitiativesRoute
  '/app/postauth': typeof AppPostauthRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tagsEdit': typeof AppTagsEditRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/worklist/': typeof AppWorklistIndexRoute
  '/app/worklist/subtasks/$workItemId': typeof AppWorklistSubtasksWorkItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/initiatives': typeof AppInitiativesRoute
  '/app/postauth': typeof AppPostauthRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tagsEdit': typeof AppTagsEditRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/worklist': typeof AppWorklistIndexRoute
  '/app/worklist/subtasks/$workItemId': typeof AppWorklistSubtasksWorkItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/initiatives': typeof AppInitiativesRoute
  '/app/postauth': typeof AppPostauthRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tagsEdit': typeof AppTagsEditRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/worklist/': typeof AppWorklistIndexRoute
  '/app/worklist/subtasks/$workItemId': typeof AppWorklistSubtasksWorkItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/initiatives'
    | '/app/postauth'
    | '/app/settings'
    | '/app/tagsEdit'
    | '/app/tasks'
    | '/app/worklist/'
    | '/app/worklist/subtasks/$workItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/initiatives'
    | '/app/postauth'
    | '/app/settings'
    | '/app/tagsEdit'
    | '/app/tasks'
    | '/app/worklist'
    | '/app/worklist/subtasks/$workItemId'
  id:
    | '__root__'
    | '/'
    | '/app/initiatives'
    | '/app/postauth'
    | '/app/settings'
    | '/app/tagsEdit'
    | '/app/tasks'
    | '/app/worklist/'
    | '/app/worklist/subtasks/$workItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppInitiativesRoute: typeof AppInitiativesRoute
  AppPostauthRoute: typeof AppPostauthRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsEditRoute: typeof AppTagsEditRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWorklistIndexRoute: typeof AppWorklistIndexRoute
  AppWorklistSubtasksWorkItemIdRoute: typeof AppWorklistSubtasksWorkItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tagsEdit': {
      id: '/app/tagsEdit'
      path: '/app/tagsEdit'
      fullPath: '/app/tagsEdit'
      preLoaderRoute: typeof AppTagsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/postauth': {
      id: '/app/postauth'
      path: '/app/postauth'
      fullPath: '/app/postauth'
      preLoaderRoute: typeof AppPostauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/initiatives': {
      id: '/app/initiatives'
      path: '/app/initiatives'
      fullPath: '/app/initiatives'
      preLoaderRoute: typeof AppInitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/worklist/': {
      id: '/app/worklist/'
      path: '/app/worklist'
      fullPath: '/app/worklist/'
      preLoaderRoute: typeof AppWorklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/worklist/subtasks/$workItemId': {
      id: '/app/worklist/subtasks/$workItemId'
      path: '/app/worklist/subtasks/$workItemId'
      fullPath: '/app/worklist/subtasks/$workItemId'
      preLoaderRoute: typeof AppWorklistSubtasksWorkItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppInitiativesRoute: AppInitiativesRoute,
  AppPostauthRoute: AppPostauthRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsEditRoute: AppTagsEditRoute,
  AppTasksRoute: AppTasksRoute,
  AppWorklistIndexRoute: AppWorklistIndexRoute,
  AppWorklistSubtasksWorkItemIdRoute: AppWorklistSubtasksWorkItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
